### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by filipetrocadoferreira** [mkocabas/pose-residual-network#1]
The method and results shown in the paper are amazing. When do you plan to release the code?

Congratulations for your work!

**Comment by mkocabas** [comment]
Thanks for the appreciation! We're trying hard to put things together and clear it for better understanding. I can't give a certain date but it's soon.

**Comment by filipetrocadoferreira** [comment]
Thanks for the code! It seems awesome and very clean. I'm trying now. I'll let you know of the results :+1:

**Comment by zhuzhu18** [comment]
> Thanks for the code! It seems awesome and very clean. I'm trying now. I'll let you know of the results

Have you reproduce the result completely?
