### ISSUE TITLE
Evaluate detection part with freezed backbone

### ISSUE THREAD

**Issue by IgorMunizS** [mkocabas/pose-residual-network#13]
Hi,
Could you please tell me how did you evaluate the detection part after training with a freezed backbone (trained for keypoint net)?
I can't achieve the mAP... not even close.

**Comment by ZhongXiaoFang** [comment]
Hi! when I retrain this code ,I placed the annotations in _./data/annotations_. Could you tell me which path should the COCO images be placed? thank you very much @IgorMunizS
