### ISSUE TITLE
Which path should the COCO images be placed ?

### ISSUE THREAD

**Issue by ZhongXiaoFang** [mkocabas/pose-residual-network#15]
Hi! thank you for you  excellent job.  When I trained on COCO dataset, the annotations are placed in 
 /data/annotations/.  but which path should the COCO images be placed ?

**Comment by salihkaragoz** [comment]
Hi @ZhongXiaoFang, 

Thanks for interest to this repo. 
Please refer to following issues. 
[12](https://github.com/salihkaragoz/pose-residual-network-pytorch/issues/12)
https://github.com/mkocabas/pose-residual-network/issues/4

Best
