### ISSUE TITLE
No module named 'gaussian

### ISSUE THREAD

**Issue by zg9uagfv** [mkocabas/pose-residual-network#18]
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src.utils import train_bbox_generator, val_bbox_generator
  File "/home/dh/github/pose-residual-network/src/utils.py", line 3, in <module>
    from gaussian import gaussian, gaussian_multi_input_mp, gaussian_multi_output
ModuleNotFoundError: No module named 'gaussian'
`

**Comment by kangwenyun** [comment]
找到了嘛?

**Comment by eehoeskrap** [comment]
from gaussian -----> from src.gaussian

evaluate.py 
from src.gaussian import gaussian, crop, gaussian_multi_input_mp

utils.py 
from src.gaussian import gaussian, gaussian_multi_input_mp, gaussian_multi_output

**Comment by eehoeskrap** [comment]
> 找到了嘛?

from gaussian -----> from src.gaussian

evaluate.py
from src.gaussian import gaussian, crop, gaussian_multi_input_mp

utils.py
from src.gaussian import gaussian, gaussian_multi_input_mp, gaussian_multi_output
