### ISSUE TITLE
 When can I see the code?

### ISSUE THREAD

**Issue by lijing271** [mkocabas/pose-residual-network#2]

**Comment by mkocabas** [comment]
We're trying hard to put things together and clear it for better understanding. I can't give a certain date but it's soon.

**Comment by lijing271** [comment]
The AR_50 of table1 in your paper seems to be wrong. It should be 88.1 instead of 0.881?

**Comment by mkocabas** [comment]
Yes it should be. Thanks for pointing out @lijing271!
