### ISSUE TITLE
A question about the speed 

### ISSUE THREAD

**Issue by FoolishMao** [mkocabas/pose-residual-network#5]
As mentioned in the paper：

> In terms of running time, our method appears to be the fastest of all multiperson
2D pose estimation methods. Depending on the number of people in the
input image, our method runs at between 27 frames/sec (FPS) (for one person
detection) and 15 FPS (for 20 person detections). For a typical COCO image,
which contains ∼3 people on average, we achieve ∼23 FPS

But，as we can see the speed of Retina  Net in the paper 《Focal Loss for Dense Object Detection》 is almost 70ms. So is there any method to speed up?

**Comment by mkocabas** [comment]
You can use a lightweight backbone as a feature extractor like MobileNet or ShuffleNet to speed it up. But, keep in mind that it comes with a drop in accuracy.
