### ISSUE TITLE
A question abount performance on embedded systems

### ISSUE THREAD

**Issue by IgorMunizS** [mkocabas/pose-residual-network#6]
Hi, great work!
I am researching the application of person detection and pose estimation in robots 
and I'm wondering if you tested the performance of the entire model on an embedded device like Jetson TX2.
Do you think it's possible to replace RetinaNet with squeezeDet(https://arxiv.org/pdf/1612.01051.pdf) for detection?

Thanks!

**Comment by mkocabas** [comment]
> I'm wondering if you tested the performance of the entire model on an embedded device like Jetson TX2.

No, we didn't run the model on an embedded device. We don't have any plan to do so in short tem.

> Do you think it's possible to replace RetinaNet with squeezeDet(https://arxiv.org/pdf/1612.01051.pdf) for detection?

I don't know about squeezeDet model, however if it has a feature extractor part like in RetinaNet or Faster-RCNN, you can use it for sure.
