### ISSUE TITLE
about the infer fps and the network

### ISSUE THREAD

**Issue by accountcwd** [mkocabas/pose-residual-network#9]
HI,i head that your implement run 23fps in GTX1080Ti .Did you use mobilenetV2 or some other lite architecture to achieve 23fps?Or you just use traditional convolution which means it can be faster using mobilenetV2?

**Comment by mkocabas** [comment]
We use a ResNet-50 to get that performance on GTX-1080ti. You can use mobilenet or variants to get higher FPS.

**Comment by ZhongXiaoFang** [comment]
Hi! thank you for you excellent job. When I trained on COCO dataset, the annotations are placed in
/data/annotations/. but which path should the COCO images be placed ? @mkocabas
